apiVersion: v1
kind: Service
metadata:
  name: realestate-api-svc
  namespace: realestate
spec:
  type: ClusterIP
  selector:
    app: realestate-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
