apiVersion: v1
kind: Service
metadata:
  name: realestate-mongo-headless
  namespace: realestate
spec:
  clusterIP: None
  selector:
    app: realestate-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: realestate-mongo
  namespace: realestate
spec:
  type: ClusterIP
  selector:
    app: realestate-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
