services:
  mongodb:
    image: mongo:7
    container_name: realestate_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      MONGO__DATABASE: ${MONGO_DATABASE}
      MONGO__CONNECTIONSTRING: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin"
    ports:
      - "5055:5000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      DOCKER: "1"
      VITE_API_PROXY_TARGET: "http://backend:5000"
      VITE_SANITY_PROJECT_ID: ${VITE_SANITY_PROJECT_ID:-}
      VITE_SANITY_DATASET: ${VITE_SANITY_DATASET:-}
      VITE_SANITY_API_VERSION: ${VITE_SANITY_API_VERSION:-2025-01-01}
      VITE_SANITY_USE_CDN: ${VITE_SANITY_USE_CDN:-true}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  
  cms:
    # This will allow us not to build cms on every build (per default)
    profiles: ["cms"]
    build:
      context: ./cms
      dockerfile: Dockerfile
    environment:
      SANITY_STUDIO_PROJECT_ID: "${SANITY_STUDIO_PROJECT_ID:-}"
      SANITY_STUDIO_DATASET: "${SANITY_STUDIO_DATASET:-}"
    ports:
      - "3333:3333"
    volumes:
      - ./cms:/app
      - /app/node_modules

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongodb_data:
