apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      project: realestate
      env: prod
    includeSelectors: false
    includeTemplates: true
    
commonAnnotations:
  owner: NinaZyabrina

replicas:
  - name: realestate-api
    count: 2
  - name: realestate-frontend
    count: 2
  - name: realestate-cms
    count: 1
  - name: realestate-mongo
    count: 1

patches:
  - path: patches/mongo-pvc.yaml
    target:
      kind: PersistentVolumeClaim
      name: realestate-mongo-pvc
