apiVersion: v1
kind: Service
metadata:
  name: realestate-api-svc
  labels:
    project: realestate
    app: realestate-api
    env: local
spec:
  type: LoadBalancer
  # on which PODs will work - to load balance the traffic
  selector:
    app: realestate-api # selecting PODs with these labels
  ports:
    - name      : http
      protocol  : TCP
      port      : 5001 # Port on load balancer
      targetPort: 5000 # Port on POD
