apiVersion: apps/v1
kind      : Deployment
metadata:
  name  : realestate-frontend
  namespace: realestate
  labels:
    project: realestate # Service will look for those PODs labels!
    app    : realestate-frontend
    env    : local
    owner  : NinaZyabrina
spec:
  replicas: 1
  selector:
    matchLabels:
      app  : realestate-frontend
# how will pods look like:
  template:
    metadata:
      labels:
        project: realestate
        app    : realestate-frontend
    spec:
      containers:
        - name : frontend
          image: zyabridos/real_estate_prod_frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name         : http
              containerPort: 80
---
apiVersion: autoscaling/v2
kind      : HorizontalPodAutoscaler
metadata:
  name  : realestate-frontend-hpa
  namespace: realestate
  labels:
    project: realestate
    app    : realestate-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind      : Deployment
    name      : realestate-frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type    : Resource
      resource:
        name  : cpu
        target:
          type              : Utilization
          averageUtilization: 80
    - type    : Resource
      resource:
        name  : memory
        target:
          type              : Utilization
          averageUtilization: 80
