apiVersion: v1
kind: Service
metadata:
  name: realestate-cms-svc
  namespace: realestate
spec:
  type: ClusterIP
  selector:
    app: realestate-cms
  ports:
    - name: http
      port: 80
      targetPort: 80
