.PHONY: help help-all help-local help-docker help-infra help-k8s help-api

help: help-all

help-all:
	@$(PRINT) ""
	@$(PRINT) "$(LIGHT_BLUE)==================================================$(RESET)"
	@$(PRINT) "$(GREEN)      Real Estate Project — Available Commands$(RESET)"
	@$(PRINT) "$(LIGHT_BLUE)==================================================$(RESET)"
	@$(PRINT) ""
	@$(PRINT) "$(PURPLE)Usage:$(RESET) make <command>"
	@$(PRINT) ""
	@$(MAKE) -s help-local
	@$(MAKE) -s help-api
	@$(MAKE) -s help-docker
	@$(MAKE) -s help-infra
	@$(MAKE) -s help-k8s
	@$(PRINT) ""

help-local:
	@$(PRINT) "$(YELLOW)Local development:$(RESET)"
	@$(PRINT) "  $(GREEN)make dev-backend$(RESET)            - Run backend locally (dotnet watch)"
	@$(PRINT) "  $(GREEN)make dev-frontend$(RESET)           - Run frontend locally (Vite)"
	@$(PRINT) "  $(GREEN)make dev-cms$(RESET)                - Run Sanity Studio locally"
	@$(PRINT) "  $(GREEN)make dev$(RESET)                    - Run backend + frontend + cms"
	@$(PRINT) ""
	@$(PRINT) "$(YELLOW)Reset / bootstrap (local):$(RESET)"
	@$(PRINT) "  $(GREEN)make backend-full-rebuild$(RESET)    - Full backend reset (NuGet, bin/obj, rebuild & run)"
	@$(PRINT) "  $(GREEN)make frontend-clean-install$(RESET)  - Full frontend reset (node_modules reinstall)"
	@$(PRINT) ""
	@$(PRINT) "$(YELLOW)Testing:$(RESET)"
	@$(PRINT) "  $(GREEN)make test-back$(RESET)               - Run backend test suite"
	@$(PRINT) ""

help-api:
	@$(PRINT) "$(YELLOW)API / Ports:$(RESET)"
	@$(PRINT) "  $(GREEN)make ping-api$(RESET)                              - Check backend health endpoint"
	@$(PRINT) "  $(GREEN)make ping-entities ENTITY=<name>$(RESET)           - Fetch list (properties | brokers | leads)"
	@$(PRINT) "  $(GREEN)make ping-entity ENTITY=<name> ID=<guid>$(RESET)   - Fetch by id"
	@$(PRINT) "  $(GREEN)make smoke-api$(RESET)                             - Run basic API smoke checks"
	@$(PRINT) "  $(GREEN)Aliases:$(RESET) ping-properties/ping-property, ping-brokers/ping-broker, ping-leads/ping-lead"
	@$(PRINT) ""
	@$(PRINT) "$(YELLOW)Seed data:$(RESET)"
	@$(PRINT) "  $(GREEN)make seed$(RESET)                  - Seed brokers + properties + leads"
	@$(PRINT) "  $(GREEN)make seed-brokers$(RESET)          - Seed brokers"
	@$(PRINT) "  $(GREEN)make seed-properties$(RESET)       - Seed properties"
	@$(PRINT) "  $(GREEN)make seed-leads$(RESET)            - Seed leads"
	@$(PRINT) ""

help-docker:
	@$(PRINT) "$(YELLOW)Docker commands:$(RESET)"
	@$(PRINT) "  $(GREEN)make build$(RESET)                  - Build Docker images"
	@$(PRINT) "  $(GREEN)make up$(RESET)                     - Start all services (foreground)"
	@$(PRINT) "  $(GREEN)make up-d$(RESET)                   - Start all services (background)"
	@$(PRINT) "  $(GREEN)make down$(RESET)                   - Stop and remove all containers"
	@$(PRINT) "  $(GREEN)make rebuild$(RESET)                - Stop, rebuild and restart all services"
	@$(PRINT) ""
	@$(PRINT) "$(YELLOW)Docker service management:$(RESET)"
	@$(PRINT) "  $(GREEN)make restart$(RESET)                - Restart core services"
	@$(PRINT) "  $(GREEN)make restart-backend$(RESET)        - Restart backend container"
	@$(PRINT) "  $(GREEN)make restart-frontend$(RESET)       - Restart frontend container"
	@$(PRINT) "  $(GREEN)make restart-db$(RESET)             - Restart mongodb container"
	@$(PRINT) "  $(GREEN)make restart-with-cms$(RESET)       - Restart core services + cms"
	@$(PRINT) ""
	@$(PRINT) "$(YELLOW)Shell inside containers:$(RESET)"
	@$(PRINT) "  $(GREEN)make sh-backend$(RESET)             - Shell into backend container"
	@$(PRINT) "  $(GREEN)make sh-frontend$(RESET)            - Shell into frontend container"
	@$(PRINT) ""
	@$(PRINT) "$(YELLOW)Cleanup:$(RESET)"
	@$(PRINT) "  $(GREEN)make prune$(RESET)                  - Remove unused Docker resources"
	@$(PRINT) "  $(GREEN)make clean$(RESET)                  - Full Docker cleanup ($(RED)danger!$(RESET))"
	@$(PRINT) ""

help-infra:
	@$(PRINT) "$(YELLOW)Infrastructure (Terraform + Ansible):$(RESET)"
	@$(PRINT) "$(BOLD)Deploy:$(RESET)"
	@$(PRINT) "  $(GREEN)make deploy-blue$(RESET)             - Terraform apply + inventory + known_hosts + ansible (prod-blue)"
	@$(PRINT) "  $(GREEN)make deploy-green$(RESET)            - Terraform apply + inventory + known_hosts + ansible (prod-green)"
	@$(PRINT) "  $(GREEN)make deploy-app-blue$(RESET)         - Only Ansible deploy app (prod-blue)"
	@$(PRINT) "  $(GREEN)make deploy-app-green$(RESET)        - Only Ansible deploy app (prod-green)"
	@$(PRINT) ""
	@$(PRINT) "$(BOLD)Terraform:$(RESET)"
	@$(PRINT) "  $(GREEN)make tf-init$(RESET)                 - Terraform init"
	@$(PRINT) "  $(GREEN)make tf-plan$(RESET)                 - Terraform plan (workspace: ENV-STACK)"
	@$(PRINT) "  $(GREEN)make tf-apply$(RESET)                - Terraform apply"
	@$(PRINT) "  $(GREEN)make tf-output$(RESET)               - Terraform output"
	@$(PRINT) "  $(GREEN)make tf-format$(RESET)               - Terraform formatting"
	@$(PRINT) "  $(GREEN)make tf-validate$(RESET)             - Terraform validate"
	@$(PRINT) "  $(GREEN)make tf-destroy$(RESET)              - Terraform destroy ($(RED)danger!$(RESET))"
	@$(PRINT) ""
	@$(PRINT) "$(BOLD)Ansible:$(RESET)"
	@$(PRINT) "  $(GREEN)make ansible-inventory$(RESET)       - Generate inventory from terraform output"
	@$(PRINT) "  $(GREEN)make ansible-known-hosts$(RESET)     - Refresh ~/.ssh/known_hosts from inventory"
	@$(PRINT) "  $(GREEN)make ansible-ping$(RESET)            - Ping hosts (ANSIBLE_LIMIT=...)"
	@$(PRINT) "  $(GREEN)make ansible-playbook$(RESET)        - Run full playbook"
	@$(PRINT) "  $(GREEN)make ansible-show-diff$(RESET)       - Dry-run --check --diff"
	@$(PRINT) "  $(GREEN)make infra-ssh$(RESET)               - SSH into host (INFRA_SSH_HOST=<ip>)"
	@$(PRINT) ""

help-k8s:
	@$(PRINT) "$(YELLOW)Kubernetes (k3d + kustomize):$(RESET)"
	@$(PRINT) "$(BOLD)Cluster:$(RESET)"
	@$(PRINT) "  $(GREEN)make k8s-up$(RESET)                    - Create k3d cluster (traefik disabled)"
	@$(PRINT) "  $(GREEN)make k8s-down$(RESET)                  - Delete k3d cluster"
	@$(PRINT) "  $(GREEN)make k8s-context$(RESET)               - Set kubectl context + namespace"
	@$(PRINT) ""
	@$(PRINT) "$(BOLD)Kustomize:$(RESET)"
	@$(PRINT) "  $(GREEN)make k8s-build$(RESET)                 - Render overlay to /tmp/realestate-<env>.yaml"
	@$(PRINT) "  $(GREEN)make k8s-validate$(RESET)              - kubectl apply --dry-run=client"
	@$(PRINT) "  $(GREEN)make k8s-apply$(RESET)                 - Apply overlay"
	@$(PRINT) "  $(GREEN)make k8s-delete$(RESET)                - Delete overlay"
	@$(PRINT) "  $(GREEN)make k8s-reset$(RESET)                 - Delete + apply + wait (current overlay)"
	@$(PRINT) "  $(GREEN)make k8s-reset-dev$(RESET)             - Reset dev overlay"
	@$(PRINT) "  $(GREEN)make k8s-reset-prod$(RESET)            - Reset prod overlay"
	@$(PRINT) ""
	@$(PRINT) "$(BOLD)Logs:$(RESET)"
	@$(PRINT) "  $(GREEN)make k8s-logs-api$(RESET)              - Tail API logs"
	@$(PRINT) "  $(GREEN)make k8s-logs-frontend$(RESET)         - Tail frontend logs"
	@$(PRINT) "  $(GREEN)make k8s-logs-cms$(RESET)              - Tail cms logs"
	@$(PRINT) "  $(GREEN)make k8s-logs-mongo$(RESET)            - Tail mongo logs"
	@$(PRINT) ""
	@$(PRINT) "$(BOLD)Port-forward:$(RESET)"
	@$(PRINT) "  $(GREEN)make k8s-pf-api$(RESET)                - Port-forward API"
	@$(PRINT) "  $(GREEN)make k8s-pf-frontend$(RESET)           - Port-forward frontend"
	@$(PRINT) "  $(GREEN)make k8s-pf-cms$(RESET)                - Port-forward cms"
	@$(PRINT) "  $(GREEN)make k8s-pf-mongo$(RESET)              - Port-forward mongo"
	@$(PRINT) ""
	@$(PRINT) "$(BOLD)Config:$(RESET)"
	@$(PRINT) "  $(GREEN)make show-k8s-config$(RESET)           - Print Kubernetes config"
	@$(PRINT) ""
