apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  realestate.dev/owner: NinaZyabrina
  realestate.dev/repo: realestate-portal

resources:
  - namespace.yaml

  - mongo/deployment.yaml
  - mongo/pvc.yaml
  - mongo/service.yaml
  - mongo/statefulset.yaml

  - api/deployment.yaml
  - api/service.yaml

  - cms/deployment.yaml
  - cms/service.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - ingress/ingress.yaml
