# Backend config
api_port: 5000
node_env: production

# Frontend
production_frontend_url: "https://realestateproject.casa"
next_public_api_url: "{{ production_frontend_url }}/api"
internal_api_url: "http://backend:5000"

# Caddy config
domain_name: "realestateproject.casa"
letsencrypt_email: "zyabrina95@gmail.com"
